<a href="https://colab.research.google.com/github/AtreyeeDas/CropsPrediction_COE/blob/main/Crops3_RandomForestClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn import preprocessing
%matplotlib inline

In [2]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/crops2.csv")
df.head(9)

N   P   K  temperature        ph    rainfall label
0  90  42  43    20.879744  6.502985  202.935536  rice
1  85  58  41    21.770462  7.038096  226.655537  rice
2  60  55  44    23.004459  7.840207  263.964248  rice
3  74  35  40    26.491096  6.980401  242.864034  rice
4  78  42  42    20.130175  7.628473  262.717340  rice
5  69  37  42    23.058049  7.073454  251.055000  rice
6  69  55  38    22.708838  5.700806  271.324860  rice
7  94  53  40    20.277744  5.718627  241.974195  rice
8  89  54  38    24.515881  6.685346  230.446236  rice

In [3]:
X = df[['N', 'P', 'K', 'temperature', 'ph', 'rainfall']] .values
X[0:5]

array([[ 90.        ,  42.        ,  43.        ,  20.87974371,
          6.50298529, 202.9355362 ],
       [ 85.        ,  58.        ,  41.        ,  21.77046169,
          7.03809636, 226.6555374 ],
       [ 60.        ,  55.        ,  44.        ,  23.00445915,
          7.84020714, 263.9642476 ],
       [ 74.        ,  35.        ,  40.        ,  26.49109635,
          6.9804009 , 242.8640342 ],
       [ 78.        ,  42.        ,  42.        ,  20.13017482,
          7.62847289, 262.7173405 ]])

In [4]:
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))
X[0:5]

array([[ 0.14549024, -0.58527158, -0.40910827, -0.82296743, -0.19955397,
        -1.07424302],
       [ 0.02835148,  0.11228969, -0.45551656, -0.66409682,  0.552013  ,
        -1.01317695],
       [-0.55734237, -0.01850305, -0.38590412, -0.44399806,  1.6785828 ,
        -0.91712736],
       [-0.22935382, -0.89045463, -0.47872071,  0.17788694,  0.47097936,
        -0.97144891],
       [-0.1356428 , -0.58527158, -0.43231242, -0.95666234,  1.38120067,
        -0.92033747]])

In [5]:
y=df['label'].values
y[0:5]

array(['rice', 'rice', 'rice', 'rice', 'rice'], dtype=object)

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (4910, 6) (4910,)
Test set: (1228, 6) (1228,)


In [7]:
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))
X[0:5]

array([[ 0.14549024, -0.58527158, -0.40910827, -0.82296743, -0.19955397,
        -1.07424302],
       [ 0.02835148,  0.11228969, -0.45551656, -0.66409682,  0.552013  ,
        -1.01317695],
       [-0.55734237, -0.01850305, -0.38590412, -0.44399806,  1.6785828 ,
        -0.91712736],
       [-0.22935382, -0.89045463, -0.47872071,  0.17788694,  0.47097936,
        -0.97144891],
       [-0.1356428 , -0.58527158, -0.43231242, -0.95666234,  1.38120067,
        -0.92033747]])

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (4910, 6) (4910,)
Test set: (1228, 6) (1228,)


In [9]:
from sklearn.ensemble import RandomForestClassifier
model= RandomForestClassifier(n_estimators=100)
model.fit(X_train,y_train)

RandomForestClassifier()

In [10]:
model.score(X_test, y_test)

0.987785016286645

In [12]:
y_predict=model.predict(X_test)
y_predict

array(['rice', 'maize', 'maize', ..., 'Urad', 'Jowar', 'cotton'],
      dtype=object)

In [13]:
y_test

array(['rice', 'maize', 'maize', ..., 'Urad', 'Jowar', 'cotton'],
      dtype=object)

In [16]:
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, model.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, y_predict))

Train set Accuracy:  0.9987780040733197
Test set Accuracy:  0.987785016286645


In [14]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_predict)

array([[ 19,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  19,   0,   0,   0,   0,   0,   1,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   1,   0,   0,   0,   0,   0,   0],
       [  0,   0,  77,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   3,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   1,   0,  22,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,  31,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0, 208,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
      